version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine
    volumes:
      - "./home:/var/jenkins_home"
    environment:
      - JAVA_OPTS=-Duser.timezone=Asia/Shanghai
    ports:
      - "8080:8080"
      - "50000:50000"
    restart: unless-stopped
